apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-v1
  labels:
    app: rust-v1
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "rust-app"
    tags.datadoghq.com/version: "v1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-v1
  template:
    metadata:
      labels:
        app: rust-v1
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "rust-app"
        tags.datadoghq.com/version: "v1.0.0"
    spec:
      containers:
        - name: rust-v1
          image: rust-v1:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/data
            - name: apmsocketpath
              mountPath: /var/run/datadog
      volumes:
        - name: config-volume
          configMap:
            name: inputdata
            items:
            - key: input.txt
              path: input.txt
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath
---
apiVersion: v1
kind: Service
metadata:
  name: rust-service-v1
spec:
  selector:
    app: rust-v1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 